### ISSUE TITLE
OOM when train LM and multiple-gpu

### ISSUE THREAD

**Issue by jungwhank** [flairNLP/flair#1512]
Hello,
I just try to train new LM, but It keeps out of memory error like this.
`RuntimeError: CUDA out of memory. Tried to allocate 4.08 GiB (GPU 0; 10.76 GiB total capacity; 8.98 GiB already allocated; 950.12 MiB free; 30.54 MiB cached)`

My data is about 6,600,000 sentences and the parameters I use are like below.
Also, GPUs are four `GeForce RTX 2080 Ti (11016MiB)`

Should I decrease batch_size or can I train parallel on multiple-GPU?

```python
# get your corpus, process forward and at the character level
corpus = TextCorpus('./corpus/',
                    dictionary,
                    is_forward_lm,
                    character_level=True)

# instantiate your language model, set hidden size and number of layers
language_model = LanguageModel(dictionary,
                               is_forward_lm,
                               hidden_size=1024,
                               nlayers=1)

# train your language model
trainer = LanguageModelTrainer(language_model, corpus)

trainer.train('resources/taggers/lm_ko_forward',
              sequence_length=250,
              mini_batch_size=32,
              max_epochs=100,
              patience=50)
```

**Comment by jungwhank** [comment]
Hi @alanakbik, I split my data more smaller and it works now. thanks for reply.  

I have some questions and need some advice for training LM.  
I'm working on training Korean flair embedding using Wiki/Opus data now,   
but perplexity stays in  about 9 ~ 10 and it doesn't decrease for a long time. (learning rates drop from 20 to 5).  I see some issues and I guess many good LMs have very low ppl like 2~5.

Also, the text that model generate during training (`log.info(self.model.generate_text())`)     
is little bit weird.

So my questions are,
1. I used wiki/opus text as it-is without any preprocessing, but I'm wondering it is right.  
Some texts are with one sentence per line, others are paragraphs per line and so on.
2. Should I just wait more for decreasing loss and perplexity? or anything you recommend to do?

my parameters are like below
```python
language_model = LanguageModel(dictionary,
                               is_forward_lm,
                               hidden_size=1024,
                               nlayers=1,
                               dropout=0.25)

trainer = LanguageModelTrainer(language_model, corpus)

trainer.train('resources/taggers/lm_ko_forward',
              sequence_length=250,
              mini_batch_size=100,
              max_epochs=300,
              patience=25,
              checkpoint=True)
```

**Comment by alanakbik** [comment]
Hello @jungwhank your parameters look good and generated text that is a little bit weird is normal since 1024 hidden states is only a small model. But if the generated text is very broken this might indicate that something is wrong.

You could try decreasing the dropout to 0.1 or even less since overfitting is rarely a problem here. If possible, you could try training a model with 2048 states which will work much better. Otherwise all looks good.

**Comment by jungwhank** [comment]
Thanks for advice @alanakbik! I will try to train a model with 2048 states and lower dropout. 

Is it ok that `using text data as it-is` that some lines are just one sentence per line, some lines are 2-3 sentences per line, and has many special characters? Is it better to split text by one sentence per line and do some preprocessing such as delete URL and some special characters?

**Comment by alanakbik** [comment]
We generally don't do any preprocessing - you can leave the text as-is since during training it is consumed as a sequence of characters anyway, so newlines are just another character in the sequence. And long special characters are often outside of your dictionary so they will be UNK'ed automatically.

**Comment by jungwhank** [comment]
Korean Language is little bit difficult to train in character level because of its characteristic, so I'm trying in various ways. I'll share if I get good results. Thanks for advice.
