### ISSUE TITLE
Training NER returning loss zero

### ISSUE THREAD

**Issue by sagorbrur** [flairNLP/flair#3326]
Hi,
I have prepared a dataset and trying to train NER. But my problem is when I try with the latest version it's returns loss zero always. Also throws Cuda out of memory problems after some iterations.
But when I switched back to version 0.10 everything worked fine. 

__Train log with the latest version:___
```
2023-10-03 12:24:31,249 epoch 1 - iter 46/469 - loss 0.00000000 - time (sec): 12.66 - samples/sec: 1513.17 - lr: 0.100000
2023-10-03 12:24:44,018 epoch 1 - iter 92/469 - loss 0.00000000 - time (sec): 25.43 - samples/sec: 1518.46 - lr: 0.100000
```

__Train log with version 0.10:__
```
2023-10-03 12:31:05,847 epoch 1 - iter 46/469 - loss 0.70203918 - samples/sec: 84.81 - lr: 0.100000
2023-10-03 12:31:20,156 epoch 1 - iter 92/469 - loss 0.48564163 - samples/sec: 102.92 - lr: 0.100000
2023-10-03 12:31:32,587 epoch 1 - iter 138/469 - loss 0.39999905 - samples/sec: 118.48 - lr: 0.100000
2023-10-03 12:31:42,920 epoch 1 - iter 184/469 - loss 0.34738959 - samples/sec: 142.53 - lr: 0.100000
2023-10-03 12:31:55,950 epoch 1 - iter 230/469 - loss 0.30741469 - samples/sec: 113.07 - lr: 0.100000
```
I have inspected the loaded datasets. It's fine, no issues there.

Training code I have used:
```py
import flair
from typing import List
from flair.trainers import ModelTrainer
from flair.models import SequenceTagger
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings, FlairEmbeddings

tag_type = 'ner'
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

# For faster training and smaller models, we can comment out the flair embeddings.
# This will significantly affect the performance though.
embedding_types: List[TokenEmbeddings] = [
    WordEmbeddings('glove'),
    FlairEmbeddings('news-forward'),
    FlairEmbeddings('news-backward'),
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

trainer.train('/content/model/conllpp',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=50,
              embeddings_storage_mode='gpu')
```

Any suggestion or help will be a great helpful. Thanks in advance.

**Comment by sagorbrur** [comment]
Hi @helpmefindaname ,
I have checked the loaded datasets. Everything is fine. 
I have checked the first sentence, the second, and so on. All contain proper tags. 
![image](https://github.com/flairNLP/flair/assets/10723655/cd0a7f31-5d0c-490b-a92e-e6d983491303)

**Comment by alanakbik** [comment]
Hello @sagorbrur, the `make_tag_dictionary` has been deprecated for a while. Could you try using `make_label_dictionary` instead? Could you also share a printout of the produced dictionary?

**Comment by sagorbrur** [comment]
Hi @alanakbik ,
I have replaced `make_tag_dictionary` with `make_label_dictionary` and here is the printout
```
tag dictionary:  Dictionary with 5 tags: <unk>, LOC, PER, ORG, MISC
```

Loss is showing correctly but now I am getting cuda out of memory problem with lower batch size. I have used 8 mini-batch sizes. But I am still getting cuda out of memory error.
![image](https://github.com/flairNLP/flair/assets/10723655/41a18a18-49f7-4c87-9446-39e69c61e288)

**Comment by alanakbik** [comment]
Try using embeddings_storage_mode='cpu' - this is the default. 'gpu' is only possible if all embeddings of the entire dataset fit into your GPU memory, which is only possible for very small datasets. Also there is really not that much of a speed boost, so setting it to 'cpu' is pretty much always your best option.

**Comment by sagorbrur** [comment]
Hi @alanakbik ,
Thank you so much. It's working now.
